#!/usr/bin/env ansible-playbook
---

- hosts: spacetime
  any_errors_fatal: yes
  vars_prompt:
    name: confirmation
    prompt: "This will delete ALL data in this Space/Time Directory instance. Are you sure? (yes/no)"
    default: no
    private: no
  tasks:
    - name: Check confirmation
      fail: msg="Supernova aborted"
      when: confirmation != "yes"

    - shell: "spacetime-supernova --config {{ config_file }}"
      register: output

    - debug: var=output.stdout_lines
