#!/usr/bin/env ansible-playbook
---

# TODO: add git branch parameter!

- hosts: spacetime
  vars:
    services:
      - spacetime-api
      - spacetime-core

  tasks:
    - include: includes/update-spacetime-service.yml name={{ item }}
      with_items: "{{ services }}"
