#!/usr/bin/env ansible-playbook
---

- hosts: spacetime
  vars:
    tools:
      - spacetime-import
      - spacetime-etl
      - spacetime-config
      - spacetime-supernova

      - spacetime-db-neo4j
      - spacetime-db-postgis
      - spacetime-db-elasticsearch

  tasks:
    - include: includes/npm-install-global.yml name={{ item }}
      with_items: "{{ tools }}"
